version: '3.2'
services:
  rabbitmq_bootcamp:
    build:
      context: ./rabbitmq
    image: robspereira/rabbitmq_bootcamp:latest
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq_bootcamp
    networks:
      - backend1
  postgres_bootcamp:
    build:
      context: ./postgres
    image: robspereira/postgres_bootcamp:latest
    ports:
      - 5431:5432
    container_name: postgres_bootcamp
    networks:
      - backend1
  bootcamp-user-api1:
    build:
      context: ../roberto-lucas-backend/app-user-api
      dockerfile: ../app-user-api/Dockerfile
    image: robspereira/app-user-api1:latest
    ports:
      - 8081:8081
    container_name: app-user-api1
    environment:
      - RABBIT_HOST=rabbitmq_bootcamp
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
    depends_on:
      - postgres_bootcamp
    networks:
      - backend1
  bootcamp-integration-api1:
    build:
      context: ../roberto-lucas-backend/app-integration-api
      dockerfile: ../app-integration-api/Dockerfile
    image: robspereira/app-integration-api1:latest
    ports:
      - 8082:8082
    container_name: app-integration-api1
    environment:
      - RABBIT_HOST=rabbitmq_bootcamp
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
    depends_on:
      - postgres_bootcamp
    networks:
      - backend1
networks:
  backend1:
    driver: "bridge"